CREATE TABLE Students
(
StudentID INT IDENTITY PRIMARY KEY,
FirstName NVARCHAR (50) NOT NULL,
LastName NVARCHAR (50) NOT NULL,
Age INT NOT NULL,
Gender NVARCHAR (20) NOT NULL,
BirthDate DATE NOT NULL,
BirthPlace NVARCHAR (200) NOT NULL,
Nationality NVARCHAR (30) NOT NULL,
Religion NVARCHAR (30) NOT NULL,
StudentPhone NVARCHAR (30) NOT NULL,
[Status] BIT NOT NULL,
StudentImage NVARCHAR (150) NOT NULL,
[Address] NVARCHAR (200) NOT NULL
)
GO


CREATE TABLE StudentDetails
(
DetailID INT IDENTITY PRIMARY KEY,
StudentID INT REFERENCES Students(StudentID),
FathersName NVARCHAR (50) NOT NULL,
FathersOccupation NVARCHAR (50) NOT NULL,
MothersName NVARCHAR (50) NOT NULL,
MothersOccupation NVARCHAR (50) NOT NULL,
GuardiansName NVARCHAR (50) NOT NULL,
GuardiansOccupation NVARCHAR (50) NOT NULL,
ParentsAddress NVARCHAR (200) NOT NULL,
ParentsPhone NVARCHAR (30) NOT NULL
)
GO
CREATE TABLE Employees
(
EmployeeID INT IDENTITY PRIMARY KEY,
FirstName NVARCHAR (30) NOT NULL,
LastName NVARCHAR (30) NOT NULL,
Salary MONEY NOT NULL,
Email NVARCHAR (50) NOT NULL,
EmployeeImage NVARCHAR (150) NOT NULL,
)
GO
CREATE TABLE Semesters
(
SemesterId INT IDENTITY (1,1) NOT NULL,
[Year] INT NOT NULL,
Semester NVARCHAR (100) NOT NULL
StudentID INT REFERENCES Students(StudentID)
)
GO